let state,selected='T3';
const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
async function request(path,input){try{const r=await fetch('/api/'+path,input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{});const result=await r.json();if(!r.ok)throw Error(result.error);state=result;render();$('toast').textContent='';}catch(e){$('toast').textContent=e.message;}}
function render(){
 const c=state.summary.counts;$('stats').replaceChildren(...[['Requirements',c.requirements],['Accessible tests',c.accessibleTests],['Accepted links',c.acceptedLinks],['Stale reviews',c.staleReviews]].map(([label,value])=>{const n=el('div',undefined,'stat');n.append(el('b',value),el('span',label));return n;}));
 $('matrix').replaceChildren(...state.summary.requirements.map(row=>{const tr=el('tr'),title=el('td',row.requirementId+' · '+row.title);title.append(el('small',row.status+' · revision '+state.data.requirements.find(r=>r.id===row.requirementId).revision));const facets=el('td');if(!row.facetIds.length)facets.append(el('span','Clarification required','missing'));for(const f of row.facetIds)facets.append(el('span',(row.coveredFacetIds.includes(f)?'● ':'○ ')+f,row.coveredFacetIds.includes(f)?'facet pass':'facet missing'));const def=el('td');def.append(el('span',row.definition,'status'));if(row.staleReviewCount)def.append(el('small',row.staleReviewCount+' stale decision(s)'));if(row.links.length)def.append(el('small',row.links.map(l=>l.testId).join(' + ')));const run=el('td');run.append(el('span',row.execution,'status'));run.append(el('small',row.execution==='fixture-pass'?'FICTIONAL · not measured here':row.execution==='unavailable'?'No eligible current execution':row.clarification||'Review source / baseline'));tr.append(title,facets,def,run);return tr;}));
 if(!state.data.tests.some(t=>t.id===selected))selected=state.data.tests[0]?.id;
 $('test').replaceChildren(...state.data.tests.map(t=>{const n=el('option',t.id+' · '+t.title);n.value=t.id;return n;}));$('test').value=selected;renderEvidence();
 $('modelstatus').textContent=state.modelState.status+(state.modelState.message?' · '+state.modelState.message:'');
}
function renderEvidence(){const t=state.data.tests.find(t=>t.id===selected);if(!t)return;$('selected').textContent=t.id+' / rev '+t.revision;const out=$('evidence');out.replaceChildren(el('h3',t.title),el('code',t.source.id+' · SHA256 '+t.source.hash));out.append(el('div',t.preconditions.map(p=>p.id+' · '+p.text).join('\n'),'pre'));for(const a of t.assertions){const n=el('div',undefined,'assertion');n.append(el('code',a.id+' [0:'+a.text.length+']'),el('div',a.text));out.append(n);}if(!t.assertions.length)out.append(el('div','Assertions removed. Title establishes no coverage.','run'));const runs=state.data.runs.filter(r=>r.testId===t.id);if(!runs.length)out.append(el('div','Execution evidence unavailable · no run fixture.','run'));for(const r of runs){const evidence=state.testEvidence.find(x=>x.testId===t.id)?.requirements.find(x=>x.requirementId==='R5');out.append(el('div','FICTIONAL '+r.id+' · '+r.softwareBaseline+' · '+evidence.status+'\n5 clients × 40 successes · max '+r.measurements.maxAcknowledgementMs+' ms. These numbers are fixture data, not measurements from this application.','run'));}
 const links=$('links');links.replaceChildren();const ps=state.proposals.filter(p=>p.testId===selected);if(!ps.length)links.append(el('p','No proposed assertion links. Titles and configuration values do not establish coverage.'));for(const p of ps){const n=el('div',undefined,'link');n.append(el('strong',p.requirementId+' → '+p.facetIds.join(' + ')+' · '+p.validation.status));for(const span of p.spans)n.append(el('p',span.assertionId+' ['+span.start+':'+span.end+'] “'+span.text+'”'));const reviewed=state.reviews.some(r=>r.state==='accepted'&&r.proposal.testId===p.testId&&r.proposal.requirementId===p.requirementId&&r.proposal.testHash===p.testHash&&r.proposal.requirementHash===p.requirementHash);const b=el('button',reviewed?'Accepted by demo reviewer':'Accept semantic coverage');b.disabled=reviewed||!p.validation.valid||p.validation.status!=='supported';b.onclick=()=>request('accept',{testId:p.testId,requirementId:p.requirementId});n.append(b);if(!p.validation.valid)n.append(el('p',p.validation.issues.join(' ')));links.append(n);}}
$('test').onchange=()=>{selected=$('test').value;renderEvidence();};$('propose').onclick=()=>request('propose',{mode:'explicit'});$('archived').onclick=()=>request('propose',{mode:'archived_model'});$('reset').onclick=()=>request('reset',{});$('invalid').onclick=()=>request('propose',{mode:'invalid_json'});$('timeout').onclick=()=>request('propose',{mode:'timeout'});
for(const [name,label] of [['r1-error-code','R1 code revision'],['t3-remove-assertions','Remove T3 assertions'],['t11-max-2001','T11 max → 2001 ms'],['r5-strict-boundary','R5 boundary → < 2000'],['test-revision-mismatch','T11 test revision'],['software-baseline-mismatch','T11 run → APP-0'],['revoke-t10','Revoke T10 access']]){const b=el('button',label);b.onclick=()=>request('mutate',{name});$('mutations').append(b);}
request('state');
