"""Capture actual review/failure/stale flows; no model or service test calls."""
import asyncio,json,os
from pathlib import Path
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parent

async def main():
    out=ROOT/'artifacts/media';out.mkdir(parents=True,exist_ok=True)
    runtime=ROOT/'private/browser-runtime';helper=runtime/'ffmpeg-1011/ffmpeg-linux';helper.parent.mkdir(parents=True,exist_ok=True)
    if not helper.exists():helper.symlink_to('/usr/bin/ffmpeg')
    os.environ['PLAYWRIGHT_BROWSERS_PATH']=str(runtime)
    async with async_playwright() as p:
        browser=await p.chromium.launch(headless=True,executable_path='/usr/bin/google-chrome',args=['--no-sandbox'])
        ctx=await browser.new_context(viewport={'width':1440,'height':1100},record_video_dir=str(ROOT/'private/video'),record_video_size={'width':1440,'height':1100})
        page=await ctx.new_page();url='http://127.0.0.1:5055'
        await page.goto(url);await page.wait_for_selector('#matrix tr');await page.locator('#reset').click();await page.wait_for_timeout(250);await page.screenshot(path=str(out/'01-original.png'),full_page=True)
        await page.locator('#propose').click();await page.wait_for_timeout(400)
        await page.locator('#links button').click();await page.wait_for_timeout(300)
        assert 'accepted' in await page.locator('#matrix tr').first.inner_text()
        await page.evaluate("async()=>{const s=await(await fetch('/api/state')).json();const p=s.proposals.find(p=>p.requirementId==='R1'&&p.testId==='T3');return fetch('/api/accept',{method:'POST',body:JSON.stringify({requirementId:'R1',testId:'T3',inspection:p})});}")
        await page.reload();await page.wait_for_selector('#matrix tr');assert '1' in await page.locator('#stats .stat').nth(2).inner_text()
        await page.screenshot(path=str(out/'02-accepted.png'),full_page=True)
        await page.get_by_role('button',name='R1 code revision',exact=True).click();await page.wait_for_timeout(350)
        assert 'stale decision' in await page.locator('#matrix tr').first.inner_text()
        await page.screenshot(path=str(out/'03-stale-review.png'),full_page=True)
        await page.locator('#reset').click();await page.locator('#propose').click();await page.locator('#test').select_option('T11');await page.locator('#links button').click();await page.wait_for_timeout(250)
        await page.screenshot(path=str(out/'04-fictional-current.png'),full_page=True)
        await page.get_by_role('button',name='T11 max → 2001 ms',exact=True).click();await page.wait_for_timeout(300)
        assert 'fixture-fail' in await page.locator('#evidence').inner_text()
        await page.screenshot(path=str(out/'05-boundary-failure.png'),full_page=True)
        await page.locator('#reset').click();await page.locator('#propose').click();await page.locator('#test').select_option('T8');await page.wait_for_timeout(250)
        assert 'stale' in await page.locator('#evidence').inner_text();await page.screenshot(path=str(out/'06-old-baseline.png'),full_page=True)
        await page.locator('#test').select_option('T10');await page.locator('#links button').click();await page.get_by_role('button',name='Revoke T10 access',exact=True).click();await page.wait_for_timeout(300)
        assert 'T10' not in await page.locator('#test').inner_text()
        await page.screenshot(path=str(out/'07-access-revoked.png'),full_page=True)
        await page.locator('#invalid').click();await page.wait_for_timeout(250);assert 'invalid-json' in await page.locator('#modelstatus').inner_text()
        await page.screenshot(path=str(out/'08-invalid-json.png'),full_page=True)
        await page.locator('#timeout').click();await page.wait_for_timeout(300);assert 'Injected demo failure' in await page.locator('#modelstatus').inner_text()
        await page.screenshot(path=str(out/'09-timeout-injected.png'),full_page=True)
        await page.locator('#reset').click();await page.locator('#archived').click();await page.locator('#test').select_option('T11');await page.wait_for_timeout(300)
        assert 'archived_model' in await page.locator('#modelstatus').inner_text()
        await page.screenshot(path=str(out/'10-recorded-qwen.png'),full_page=True)
        await page.locator('#reset').click();await page.locator('#propose').click();await page.locator('#test').select_option('T3');await page.get_by_role('button',name='Remove T3 assertions',exact=True).click();await page.wait_for_timeout(250)
        assert 'Assertions removed' in await page.locator('#evidence').inner_text()
        await page.screenshot(path=str(out/'11-assertions-removed.png'),full_page=True)
        await page.locator('#reset').click();await page.wait_for_timeout(600)
        source=page.locator('button.source-link').first;await source.focus();await page.keyboard.press('Enter');await page.wait_for_timeout(200)
        assert await page.locator('#test').input_value()=='T2'
        requirement=page.locator('summary').first;await requirement.focus();await page.keyboard.press('Enter')
        assert await page.locator('details').first.evaluate('(n)=>n.open')
        await page.screenshot(path=str(out/'12-keyboard-source.png'),full_page=True)
        video=page.video;await ctx.close();await video.save_as(str(out/'review-demo.webm'))
        for width in [360,390]:
            mobile=await browser.new_page(viewport={'width':width,'height':950},device_scale_factor=1)
            await mobile.goto(url);await mobile.wait_for_selector('#matrix tr');await mobile.screenshot(path=str(out/f'desk-{width}.png'),full_page=True)
            await mobile.goto('about:blank')
            await mobile.set_content('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#171f2c"><img id="graph" style="width:'+str(width)+'px;display:block" src="data:image/svg+xml;base64,'+__import__('base64').b64encode((ROOT/'docs/architecture.svg').read_bytes()).decode()+'"></body></html>')
            await mobile.locator('#graph').evaluate('(img)=>img.decode()')
            await mobile.screenshot(path=str(out/f'diagram-{width}.png'),full_page=True)
            await mobile.close()
        diagram=await browser.new_page(viewport={'width':420,'height':700})
        await diagram.set_content('<!doctype html><body style="margin:0"><img id="graph" width="420" height="700" src="data:image/svg+xml;base64,'+__import__('base64').b64encode((ROOT/'docs/architecture.svg').read_bytes()).decode()+'"></body>');await diagram.locator('#graph').evaluate('(img)=>img.decode()');await diagram.screenshot(path=str(ROOT/'docs/architecture.png'))
        await browser.close()
    (ROOT/'artifacts/browser-checks.json').write_text(json.dumps({'actualBrowser':'Playwright Chromium','flows':['zero original','proposal acceptance','repeated acceptance idempotent','requirement revision stale','fictional current run','2001 boundary failure','APP-0 stale','access revoked','injected invalid JSON','injected timeout','recorded Qwen artifact','assertions removed','keyboard original source navigation'],'nativeFacetRows':11,'separateDefinitionAcceptanceRunColumns':True,'widths':[360,390],'modelCalledDuringBrowserCapture':False,'actualServicePerformanceMeasured':False},indent=2))

if __name__=='__main__':asyncio.run(main())
